name: "Smart Test Generator"
description: "Generate Python tests with AI on GitHub runners"
author: "Pradyumn"
branding:
  icon: "zap"
  color: "blue"

inputs:
  paths:
    description: "Directory to scan (e.g., src/ or .  for current directory)"
    required: true
  model:
    description: "Optional model id (not currently supported by CLI)"
    required: false
    default: ""
  output-dir:
    description: "Directory to write generated tests"
    required: false
    default: "generated-tests"
  gemini-api-key:
    description: "Gemini API key (pass from secrets)"
    required: true
  framework:
    description: "Test framework (pytest or unittest)"
    required: false
    default: "pytest"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install package
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ${{ github.action_path }}

    - name: Run smart-test batch command
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
      run: |
        set -euo pipefail
        smart-test batch "${{ inputs.paths }}" \
          --output-dir "${{ inputs.output-dir }}" \
          --framework "${{ inputs.framework }}"