name: "Smart Test Generator"
description: "AI-powered Python test generation using LLM. Generate comprehensive pytest/unittest tests automatically for your Python code."
author: "Pradyumn"
branding:
  icon: "zap"
  color: "blue"

inputs:
  paths:
    description: |
      Path(s) to Python files or directories to scan.
      Examples: 'src/' (directory), 'app.py' (single file), 'src/,lib/utils.py' (multiple paths - comma-separated)
    required: true
  
  gemini-api-key:
    description: |
      Your Gemini API Key - Get FREE key at: https://aistudio.google.com/app/apikey
      Store as repository secret in Settings → Secrets → Actions → New secret
    required: true
  
  model:
    description: |
      Gemini AI model to use.
      Options: models/gemini-2.0-flash (Fast, recommended), models/gemini-2.5-flash (Latest), models/gemini-pro-latest (Most capable)
    required: false
    default: "models/gemini-2.0-flash"
  
  framework:
    description: |
      Python testing framework.
      Options: 'pytest' (recommended) or 'unittest'
    required: false
    default: "pytest"
  
  output-dir:
    description: |
      Directory where generated test files will be saved.
      Example: 'tests/generated' or 'generated-tests'
    required: false
    default: "generated-tests"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install package
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ${{ github.action_path }}

    - name: Create output directory
      shell: bash
      run: mkdir -p "${{ inputs.output-dir }}"

    - name: Debug - List files to be scanned
      shell: bash
      run: |
        echo "Scanning paths: ${{ inputs.paths }}"
        IFS=',' read -ra PATHS <<< "${{ inputs.paths }}"
        for path in "${PATHS[@]}"; do
          path=$(echo "$path" | xargs)
          if [ -f "$path" ]; then
            if [[ "$path" == *.py ]]; then
              echo "  ✓ Python file: $path"
            else
              echo "  ⚠ Not a Python file: $path"
            fi
          elif [ -d "$path" ]; then
            echo "  ✓ Directory: $path"
            file_count=$(find "$path" -name "*.py" -type f 2>/dev/null | wc -l)
            echo "    Found $file_count Python files"
          else
            echo "  ✗ Not found: $path"
          fi
        done

    - name: Run smart-test command
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
      run: |
        BEFORE_COUNT=$(find "${{ inputs.output-dir }}" -name "test_*.py" -type f 2>/dev/null | wc -l)
        
        IFS=',' read -ra PATHS <<< "${{ inputs.paths }}"
        
        SUCCESS_PATHS=0
        FAIL_PATHS=0
        
        for path in "${PATHS[@]}"; do
          path=$(echo "$path" | xargs)
          
          if [ -z "$path" ]; then
            continue
          fi
          
          if [ -f "$path" ]; then
            if [[ "$path" != *.py ]]; then
              echo "  ⚠ Skipping non-Python file: $path"
              FAIL_PATHS=$((FAIL_PATHS + 1))
              continue
            fi
            
            echo "Generating test for file: $path"
            
            SAFE_PATH=$(echo "$path" | sed 's/[^a-zA-Z0-9._-]/_/g')
            FILE_NAME=$(basename "$path")
            OUTPUT_FILE="${{ inputs.output-dir }}/test_${FILE_NAME}"
            
            if [ -f "$OUTPUT_FILE" ]; then
              echo "  ⚠ Warning: $OUTPUT_FILE already exists, using unique name"
              OUTPUT_FILE="${{ inputs.output-dir }}/test_${SAFE_PATH}"
            fi
            
            if smart-test generate "$path" \
              --output "$OUTPUT_FILE" \
              --framework "${{ inputs.framework }}" \
              --model "${{ inputs.model }}"; then
              SUCCESS_PATHS=$((SUCCESS_PATHS + 1))
              echo "  ✓ Success: $OUTPUT_FILE"
            else
              FAIL_PATHS=$((FAIL_PATHS + 1))
              echo "  ✗ Failed: $path"
            fi
            
          elif [ -d "$path" ]; then
            echo "Generating tests for directory: $path"
            FILE_COUNT=$(find "$path" -name "*.py" -type f 2>/dev/null | wc -l)
            echo "  Found $FILE_COUNT Python files to process"
            
            if smart-test batch "$path" \
              --output-dir "${{ inputs.output-dir }}" \
              --framework "${{ inputs.framework }}" \
              --model "${{ inputs.model }}"; then
              SUCCESS_PATHS=$((SUCCESS_PATHS + 1))
              echo "  ✓ Success: $path"
            else
              FAIL_PATHS=$((FAIL_PATHS + 1))
              echo "  ✗ Failed: $path"
            fi
          else
            echo "  ⚠ Warning: Path not found or invalid: $path"
            FAIL_PATHS=$((FAIL_PATHS + 1))
          fi
        done
        
        AFTER_COUNT=$(find "${{ inputs.output-dir }}" -name "test_*.py" -type f 2>/dev/null | wc -l)
        NEW_FILES=$((AFTER_COUNT - BEFORE_COUNT))
        
        echo ""
        echo "========================================="
        echo "Summary:"
        echo "  Paths processed: $((SUCCESS_PATHS + FAIL_PATHS))"
        echo "  ✓ Successful paths: $SUCCESS_PATHS"
        echo "  ✗ Failed paths: $FAIL_PATHS"
        echo "  📄 New test files generated: $NEW_FILES"
        echo "  📁 Total test files in output: $AFTER_COUNT"
        echo "========================================="
        
        if [ $SUCCESS_PATHS -eq 0 ] && [ $FAIL_PATHS -gt 0 ]; then
          echo "Error: All paths failed to generate tests"
          exit 1
        fi

    - name: Debug - List generated files
      shell: bash
      run: |
        echo "Generated files in ${{ inputs.output-dir }}:"
        ls -la "${{ inputs.output-dir }}" || echo "Output directory is empty or doesn't exist"